const ITEMS = {
      APPLE: {
        name: 'Apple',
        slug: 'APPLE', 
        use:  'HOLDS',
        icon: 'APPLE',
        type: 'FOOD',
        description: '',
        actions: [ {
            name: 'EAT',
            consume: false,
            transition: 'APPLE_TRASH',
          },],
        stack: 3,
        stacks: [        ],
    },
      APPLE_TRASH: {
        name: 'Apple Core',
        slug: 'APPLE_TRASH', 
        use:  'HOLDS',
        icon: 'APPLE_TRASH',
        type: 'TRASH',
        description: '',
        actions: [ {
            name: 'CHUCK',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      BANANA: {
        name: 'Banana',
        slug: 'BANANA', 
        use:  'HOLDS',
        icon: 'BANANA',
        type: 'FOOD',
        description: 'Platonically ripe. You have a hard time remembering that yellow Giggle Taffy is modeled after the banana, and not the other way around.',
        actions: [ {
            name: 'EAT',
            consume: false,
            transition: 'BANANA_TRASH',
          },],
        stack: 3,
        stacks: [        ],
    },
      BANANA_TRASH: {
        name: 'Banana Peel',
        slug: 'BANANA_TRASH', 
        use:  'HOLDS',
        icon: 'BANANA_TRASH',
        type: 'TRASH',
        description: 'A slapstick icon.',
        actions: [ {
            name: 'CHUCK',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      MUFFIN_BERRY: {
        name: 'Berry Muffin',
        slug: 'MUFFIN_BERRY', 
        use:  'HOLDS',
        icon: 'MUFFIN_BERRY',
        type: 'FOOD',
        description: '',
        actions: [ {
            name: 'EAT',
            consume: true,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      CRAYON_BLUE: {
        name: 'Blue Crayon',
        slug: 'CRAYON_BLUE', 
        use:  'HOLDS',
        icon: 'CRAYON_BLUE',
        type: 'CRAYON',
        description: '',
        actions: [ {
            name: 'DRAW',
            consume: false,
            transition: false,
          },],
        stack: 5,
        stacks: [        ],
    },
      NOTEBOOK_BLUE: {
        name: 'Blue Notebook',
        slug: 'NOTEBOOK_BLUE', 
        use:  'HOLDS',
        icon: 'NOTEBOOK_BLUE',
        type: 'NOTEBOOK',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          }, {
            name: 'READ',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      CRAYON_BROWN: {
        name: 'Brown Crayon',
        slug: 'CRAYON_BROWN', 
        use:  'HOLDS',
        icon: 'CRAYON_BROWN',
        type: 'CRAYON',
        description: '',
        actions: [ {
            name: 'DRAW',
            consume: false,
            transition: false,
          },],
        stack: 5,
        stacks: [        ],
    },
      BANANA_BRUISED: {
        name: 'Bruised Banana',
        slug: 'BANANA_BRUISED', 
        use:  'HOLDS',
        icon: 'BANANA_BRUISED',
        type: 'FOOD',
        description: 'Pretty sure it’s still good. Borderline banana bread worthy.',
        actions: [ {
            name: 'EAT',
            consume: false,
            transition: 'BANANA_TRASH',
          },],
        stack: 3,
        stacks: [        ],
    },
      DIGITAL_WATCH: {
        name: 'BSC-100 Digital Watch',
        slug: 'DIGITAL_WATCH', 
        use:  'WEARS',
        icon: 'DIGITAL_WATCH',
        type: 'WATCH',
        description: '',
        actions: [ {
            name: 'READ',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      BUS_TICKET: {
        name: 'Bus Ticket',
        slug: 'BUS_TICKET', 
        use:  'HOLDS',
        icon: 'BUS_TICKET',
        type: 'TICKET',
        description: '',
        actions: [ {
            name: 'READ',
            consume: false,
            transition: false,
          },],
        stack: 5,
        stacks: [        ],
    },
      CUPCAKE_CREAM: {
        name: 'Buttercream Cupcake',
        slug: 'CUPCAKE_CREAM', 
        use:  'HOLDS',
        icon: 'CUPCAKE_CREAM',
        type: 'FOOD',
        description: '',
        actions: [ {
            name: 'EAT',
            consume: true,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      SODA_RED: {
        name: 'Cane Soda',
        slug: 'SODA_RED', 
        use:  'HOLDS',
        icon: 'SODA_RED',
        type: 'DRINK',
        description: 'An often flat, sometimes metallic generic soda.',
        actions: [ {
            name: 'DRINK',
            consume: false,
            transition: 'SODA_RED_TRASH',
          },],
        stack: 1,
        stacks: [        ],
    },
      BACKPACK_CANVAS: {
        name: 'Canvas Backpack',
        slug: 'BACKPACK_CANVAS', 
        use:  'WEARS',
        icon: 'BACKPACK_CANVAS',
        type: 'BAG',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          },],
        stack: 1,
        stacks: [        ],
slots: '6',
items: []    },
      CASSEROLE_DISH_1: {
        name: 'Casserole Dish 1',
        slug: 'CASSEROLE_DISH_1', 
        use:  'HOLDS',
        icon: 'CASSEROLE_DISH_1',
        type: 'CASSEROLE_DISH',
        description: '',
        actions: [ {
            name: 'PLACE',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      CASSEROLE_DISH_2: {
        name: 'Casserole Dish 2',
        slug: 'CASSEROLE_DISH_2', 
        use:  'HOLDS',
        icon: 'CASSEROLE_DISH_2',
        type: 'CASSEROLE_DISH',
        description: '',
        actions: [ {
            name: 'PLACE',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      CASSEROLE_DISH_3: {
        name: 'Casserole Dish 3',
        slug: 'CASSEROLE_DISH_3', 
        use:  'HOLDS',
        icon: 'CASSEROLE_DISH_3',
        type: 'CASSEROLE_DISH',
        description: '',
        actions: [ {
            name: 'PLACE',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      CASSEROLE_DISH_4: {
        name: 'Casserole Dish 4',
        slug: 'CASSEROLE_DISH_4', 
        use:  'HOLDS',
        icon: 'CASSEROLE_DISH_4',
        type: 'CASSEROLE_DISH',
        description: '',
        actions: [ {
            name: 'PLACE',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      CASSEROLE_DISH_5: {
        name: 'Casserole Dish 5',
        slug: 'CASSEROLE_DISH_5', 
        use:  'HOLDS',
        icon: 'CASSEROLE_DISH_5',
        type: 'CASSEROLE_DISH',
        description: '',
        actions: [ {
            name: 'PLACE',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      CASSEROLE_DISH_6: {
        name: 'Casserole Dish 6',
        slug: 'CASSEROLE_DISH_6', 
        use:  'HOLDS',
        icon: 'CASSEROLE_DISH_6',
        type: 'CASSEROLE_DISH',
        description: '',
        actions: [ {
            name: 'PLACE',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      CASSETTE_BLACK: {
        name: 'Cassette Tape Black',
        slug: 'CASSETTE_BLACK', 
        use:  'HOLDS',
        icon: 'CASSETTE_BLACK',
        type: 'MEDIA',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      CASSETTE_BLUE: {
        name: 'Cassette Tape Blue',
        slug: 'CASSETTE_BLUE', 
        use:  'HOLDS',
        icon: 'CASSETTE_BLUE',
        type: 'MEDIA',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      CASSETTE_RED: {
        name: 'Cassette Tape Red',
        slug: 'CASSETTE_RED', 
        use:  'HOLDS',
        icon: 'CASSETTE_RED',
        type: 'MEDIA',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      CASSETTE_YELLOW: {
        name: 'Cassette Tape Yellow',
        slug: 'CASSETTE_YELLOW', 
        use:  'HOLDS',
        icon: 'CASSETTE_YELLOW',
        type: 'MEDIA',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      CHINESE_FOOD: {
        name: 'Chinese Food',
        slug: 'CHINESE_FOOD', 
        use:  'HOLDS',
        icon: 'CHINESE_FOOD',
        type: 'DELIVERY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      CHINESE_FOOD_MARKED: {
        name: 'Chinese Food (Marked)',
        slug: 'CHINESE_FOOD_MARKED', 
        use:  'HOLDS',
        icon: 'CHINESE_FOOD_MARKED',
        type: 'DELIVERY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      CUPCAKE_CHOCOLATE: {
        name: 'Chocolate Cupcake',
        slug: 'CUPCAKE_CHOCOLATE', 
        use:  'HOLDS',
        icon: 'CUPCAKE_CHOCOLATE',
        type: 'FOOD',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      PUDDING_CHOCOLATE: {
        name: 'Chocolate Pudding',
        slug: 'PUDDING_CHOCOLATE', 
        use:  'HOLDS',
        icon: 'PUDDING_CHOCOLATE',
        type: 'FOOD',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      LUNCH_BAG_CLEAN: {
        name: 'Clean Lunch Bag',
        slug: 'LUNCH_BAG_CLEAN', 
        use:  'HOLDS',
        icon: 'LUNCH_BAG_CLEAN',
        type: 'BAG',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
slots: '2',
items: []    },
      PAPER_BAG_CLEAN: {
        name: 'Clean Paper Bag',
        slug: 'PAPER_BAG_CLEAN', 
        use:  'HOLDS',
        icon: 'PAPER_BAG_CLEAN',
        type: 'BAG',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
slots: '3',
items: []    },
      CLOVES: {
        name: 'Cloves',
        slug: 'CLOVES', 
        use:  'HOLDS',
        icon: 'CLOVES',
        type: 'SMOKES',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      COOKIE: {
        name: 'Cookie',
        slug: 'COOKIE', 
        use:  'HOLDS',
        icon: 'COOKIE',
        type: 'FOOD',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      CRAYON_PACK: {
        name: 'Cray-oh-no Crayons',
        slug: 'CRAYON_PACK', 
        use:  'HOLDS',
        icon: 'CRAYON_PACK',
        type: 'PRODUCT',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          }, {
            name: 'READ',
            consume: false,
            transition: false,
          },],
        stack: 1,
        stacks: [        ],
    },
      BEER: {
        name: 'Driver’s Brew',
        slug: 'BEER', 
        use:  'HOLDS',
        icon: 'BEER',
        type: 'HOOCH',
        description: 'The label shows a sunglasses wearing dog driving a convertible up an S shaped road, one paw slung over a poodle’s shoulder. ‘Ride Life’s Curves’ 4.5% ABV',
        actions: [ {
            name: 'DRINK',
            consume: false,
            transition: false,
          },],
        stack: 1,
        stacks: [        ],
    },
      SODA_RED_TRASH: {
        name: 'Empty Cane Soda Can',
        slug: 'SODA_RED_TRASH', 
        use:  'HOLDS',
        icon: 'SODA_RED_TRASH',
        type: 'TRASH',
        description: '',
        actions: [ {
            name: 'CHUCK',
            consume: false,
            transition: false,
          },],
        stack: 1,
        stacks: [        ],
    },
      ENVELOPE_BACK_1: {
        name: 'Envelope (Back)',
        slug: 'ENVELOPE_BACK_1', 
        use:  'HOLDS',
        icon: 'ENVELOPE_BACK_1',
        type: 'MAIL',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          }, {
            name: 'FLIP',
            consume: false,
            transition: 'ENVELOPE_FRONT_1',
          },],
        stack: 3,
        stacks: [        ],
    },
      ENVELOPE_FRONT_1: {
        name: 'Envelope (Front)',
        slug: 'ENVELOPE_FRONT_1', 
        use:  'HOLDS',
        icon: 'ENVELOPE_FRONT_1',
        type: 'MAIL',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          }, {
            name: 'FLIP',
            consume: false,
            transition: 'ENVELOPE_BACK_1',
          },],
        stack: 3,
        stacks: [        ],
    },
      FANNY_PACK: {
        name: 'Fanny Pack',
        slug: 'FANNY_PACK', 
        use:  'HOLDS',
        icon: 'FANNY_PACK',
        type: 'BAG',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
slots: '3',
items: []    },
      FLOPPY_BLUE: {
        name: 'Floppy Disk Blue',
        slug: 'FLOPPY_BLUE', 
        use:  'HOLDS',
        icon: 'FLOPPY_BLUE',
        type: 'MEDIA',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      FLOPPY_GREEN: {
        name: 'Floppy Disk Green',
        slug: 'FLOPPY_GREEN', 
        use:  'HOLDS',
        icon: 'FLOPPY_GREEN',
        type: 'MEDIA',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      FLOPPY_RED: {
        name: 'Floppy Disk Red',
        slug: 'FLOPPY_RED', 
        use:  'HOLDS',
        icon: 'FLOPPY_RED',
        type: 'MEDIA',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      FLOPPY_YELLOW: {
        name: 'Floppy Disk Yellow',
        slug: 'FLOPPY_YELLOW', 
        use:  'HOLDS',
        icon: 'FLOPPY_YELLOW',
        type: 'MEDIA',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      SODA_GREEN: {
        name: 'Fresco Lime-o Soda(TM)',
        slug: 'SODA_GREEN', 
        use:  'HOLDS',
        icon: 'SODA_GREEN',
        type: 'DRINK',
        description: 'A refreshing, caffeine-free, high-fructose corn syrup loaded carbonated beverage.',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      PIZZA_BOX_CLEAN: {
        name: 'Fresh Pizza Box',
        slug: 'PIZZA_BOX_CLEAN', 
        use:  'HOLDS',
        icon: 'PIZZA_BOX_CLEAN',
        type: 'DELIVERY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      LUNCH_BAG_GREASY: {
        name: 'Greasy Lunch Bag',
        slug: 'LUNCH_BAG_GREASY', 
        use:  'HOLDS',
        icon: 'LUNCH_BAG_GREASY',
        type: 'BAG',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
slots: '2',
items: []    },
      PAPER_BAG_GREASY: {
        name: 'Greasy Paper Bag',
        slug: 'PAPER_BAG_GREASY', 
        use:  'HOLDS',
        icon: 'PAPER_BAG_GREASY',
        type: 'BAG',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
slots: '3',
items: []    },
      PIZZA_BOX_GREASY: {
        name: 'Greasy Pizza Box',
        slug: 'PIZZA_BOX_GREASY', 
        use:  'HOLDS',
        icon: 'PIZZA_BOX_GREASY',
        type: 'DELIVERY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      BACKPACK_GREEN: {
        name: 'Green Backpack',
        slug: 'BACKPACK_GREEN', 
        use:  'WEARS',
        icon: 'BACKPACK_GREEN',
        type: 'BAG',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
slots: '6',
items: []    },
      CRAYON_GREEN: {
        name: 'Green Crayon',
        slug: 'CRAYON_GREEN', 
        use:  'HOLDS',
        icon: 'CRAYON_GREEN',
        type: 'CRAYON',
        description: '',
        actions: [ {
            name: 'DRAW',
            consume: false,
            transition: false,
          },],
        stack: 5,
        stacks: [        ],
    },
      NOTEBOOK_GREEN: {
        name: 'Green Notebook',
        slug: 'NOTEBOOK_GREEN', 
        use:  'HOLDS',
        icon: 'NOTEBOOK_GREEN',
        type: 'NOTEBOOK',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          }, {
            name: 'READ',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      HEDGE_TRIMMERS: {
        name: 'Hedge Trimmers',
        slug: 'HEDGE_TRIMMERS', 
        use:  'USES',
        icon: 'HEDGE_TRIMMERS',
        type: 'TOOL',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      VHS_HOME: {
        name: 'Home Video VHS',
        slug: 'VHS_HOME', 
        use:  'HOLDS',
        icon: 'VHS_HOME',
        type: 'MEDIA',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      INSTANT_NOODLES_RED: {
        name: 'Instant Noodles Beef',
        slug: 'INSTANT_NOODLES_RED', 
        use:  'HOLDS',
        icon: 'INSTANT_NOODLES_RED',
        type: 'FOOD',
        description: '',
        actions: [ {
            name: 'EAT',
            consume: true,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      INSTANT_NOODLES_ORANGE: {
        name: 'Instant Noodles Chicken',
        slug: 'INSTANT_NOODLES_ORANGE', 
        use:  'HOLDS',
        icon: 'INSTANT_NOODLES_ORANGE',
        type: 'FOOD',
        description: '',
        actions: [ {
            name: 'EAT',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      INSTANT_NOODLES_BLUE: {
        name: 'Instant Noodles Shrimp',
        slug: 'INSTANT_NOODLES_BLUE', 
        use:  'HOLDS',
        icon: 'INSTANT_NOODLES_BLUE',
        type: 'FOOD',
        description: '',
        actions: [ {
            name: 'EAT',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      INSTANT_NOODLES_GREEN: {
        name: 'Instant Noodles Vegetables',
        slug: 'INSTANT_NOODLES_GREEN', 
        use:  'HOLDS',
        icon: 'INSTANT_NOODLES_GREEN',
        type: 'FOOD',
        description: '',
        actions: [ {
            name: 'EAT',
            consume: true,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      KEY_1: {
        name: 'Key 1',
        slug: 'KEY_1', 
        use:  'HOLDS',
        icon: 'KEY_1',
        type: 'KEY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      KEY_10: {
        name: 'Key 10',
        slug: 'KEY_10', 
        use:  'HOLDS',
        icon: 'KEY_10',
        type: 'KEY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      KEY_11: {
        name: 'Key 11',
        slug: 'KEY_11', 
        use:  'HOLDS',
        icon: 'KEY_11',
        type: 'KEY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      KEY_12: {
        name: 'Key 12',
        slug: 'KEY_12', 
        use:  'HOLDS',
        icon: 'KEY_12',
        type: 'KEY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      KEY_2: {
        name: 'Key 2',
        slug: 'KEY_2', 
        use:  'HOLDS',
        icon: 'KEY_2',
        type: 'KEY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      KEY_3: {
        name: 'Key 3',
        slug: 'KEY_3', 
        use:  'HOLDS',
        icon: 'KEY_3',
        type: 'KEY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      KEY_4: {
        name: 'Key 4',
        slug: 'KEY_4', 
        use:  'HOLDS',
        icon: 'KEY_4',
        type: 'KEY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      KEY_5: {
        name: 'Key 5',
        slug: 'KEY_5', 
        use:  'HOLDS',
        icon: 'KEY_5',
        type: 'KEY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      KEY_6: {
        name: 'Key 6',
        slug: 'KEY_6', 
        use:  'HOLDS',
        icon: 'KEY_6',
        type: 'KEY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      KEY_7: {
        name: 'Key 7',
        slug: 'KEY_7', 
        use:  'HOLDS',
        icon: 'KEY_7',
        type: 'KEY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      KEY_8: {
        name: 'Key 8',
        slug: 'KEY_8', 
        use:  'HOLDS',
        icon: 'KEY_8',
        type: 'KEY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      KEY_9: {
        name: 'Key 9',
        slug: 'KEY_9', 
        use:  'HOLDS',
        icon: 'KEY_9',
        type: 'KEY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      BACKPACK_BROWN: {
        name: 'Leather Rucksack',
        slug: 'BACKPACK_BROWN', 
        use:  'WEARS',
        icon: 'BACKPACK_BROWN',
        type: 'BAG',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
slots: '6',
items: []    },
      LIBRARY_CARD: {
        name: 'Library Card',
        slug: 'LIBRARY_CARD', 
        use:  'HOLDS',
        icon: 'LIBRARY_CARD',
        type: 'ID',
        description: 'Your local passport to global consciousness. You may check out up to three (3) books at a time.',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      LIGHTER: {
        name: 'Lighter',
        slug: 'LIGHTER', 
        use:  'USES',
        icon: 'LIGHTER',
        type: 'TOOL',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      LOTTO: {
        name: 'Lotto Ticket',
        slug: 'LOTTO', 
        use:  'HOLDS',
        icon: 'LOTTO',
        type: 'TICKET',
        description: '',
        actions: [ {
            name: 'READ',
            consume: false,
            transition: false,
          },],
        stack: 5,
        stacks: [        ],
    },
      RABBITS_FOOT: {
        name: 'Lucky Rabbit’s Foot',
        slug: 'RABBITS_FOOT', 
        use:  'HOLDS',
        icon: 'RABBITS_FOOT',
        type: 'CHARM',
        description: '',
        actions: [ {
            name: 'WAIT',
            consume: false,
            transition: false,
          },],
        stack: 5,
        stacks: [        ],
    },
      CIGARETTE_MENTHOL: {
        name: 'Menthol Frost',
        slug: 'CIGARETTE_MENTHOL', 
        use:  'HOLDS',
        icon: 'CIGARETTE_MENTHOL',
        type: 'SMOKES',
        description: 'A pack of Menthol Frost Cigarettes. Smells sort of like spearmint. Mom’s brand. Manufactured by the Reaper Company.',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      MUFFIN: {
        name: 'Muffin',
        slug: 'MUFFIN', 
        use:  'HOLDS',
        icon: 'MUFFIN',
        type: 'FOOD',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      MUG_1: {
        name: 'Mug 1',
        slug: 'MUG_1', 
        use:  'HOLDS',
        icon: 'MUG_1',
        type: 'MUG',
        description: '',
        actions: [ {
            name: 'DRINK',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      MUG_2: {
        name: 'Mug 2',
        slug: 'MUG_2', 
        use:  'HOLDS',
        icon: 'MUG_2',
        type: 'MUG',
        description: '',
        actions: [ {
            name: 'DRINK',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      MUG_3: {
        name: 'Mug 3',
        slug: 'MUG_3', 
        use:  'HOLDS',
        icon: 'MUG_3',
        type: 'MUG',
        description: '',
        actions: [ {
            name: 'DRINK',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      MUG_4: {
        name: 'Mug 4',
        slug: 'MUG_4', 
        use:  'HOLDS',
        icon: 'MUG_4',
        type: 'MUG',
        description: '',
        actions: [ {
            name: 'DRINK',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      MUG_5: {
        name: 'Mug 5',
        slug: 'MUG_5', 
        use:  'HOLDS',
        icon: 'MUG_5',
        type: 'MUG',
        description: '',
        actions: [ {
            name: 'DRINK',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      MUG_6: {
        name: 'Mug 6',
        slug: 'MUG_6', 
        use:  'HOLDS',
        icon: 'MUG_6',
        type: 'MUG',
        description: '',
        actions: [ {
            name: 'DRINK',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      MUG_7: {
        name: 'Mug 7',
        slug: 'MUG_7', 
        use:  'HOLDS',
        icon: 'MUG_7',
        type: 'MUG',
        description: '',
        actions: [ {
            name: 'DRINK',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      MUG_8: {
        name: 'Mug 8',
        slug: 'MUG_8', 
        use:  'HOLDS',
        icon: 'MUG_8',
        type: 'MUG',
        description: '',
        actions: [ {
            name: 'DRINK',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      MUG_9: {
        name: 'Mug 9',
        slug: 'MUG_9', 
        use:  'HOLDS',
        icon: 'MUG_9',
        type: 'MUG',
        description: '',
        actions: [ {
            name: 'DRINK',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      NEWSPAPER: {
        name: 'Newspaper',
        slug: 'NEWSPAPER', 
        use:  'HOLDS',
        icon: 'NEWSPAPER',
        type: 'JOURNALISM',
        description: '',
        actions: [ {
            name: 'READ',
            consume: false,
            transition: false,
          }, {
            name: 'LITTER',
            consume: false,
            transition: false,
          }, {
            name: 'CHUCK',
            consume: false,
            transition: false,
          },],
        stack: 4,
        stacks: [        ],
    },
      SARDINES: {
        name: 'Open Pigeon of the Sea Sardines',
        slug: 'SARDINES', 
        use:  'HOLDS',
        icon: 'SARDINES',
        type: 'FOOD',
        description: 'A tidy row of oily, factory-farmed noodle fish, ready for a handful of crackers.',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      CRAYON_ORANGE: {
        name: 'Orange Crayon',
        slug: 'CRAYON_ORANGE', 
        use:  'HOLDS',
        icon: 'CRAYON_ORANGE',
        type: 'CRAYON',
        description: '',
        actions: [ {
            name: 'DRAW',
            consume: false,
            transition: false,
          },],
        stack: 5,
        stacks: [        ],
    },
      CUPCAKE_PINK: {
        name: 'Pink Cupcake',
        slug: 'CUPCAKE_PINK', 
        use:  'HOLDS',
        icon: 'CUPCAKE_PINK',
        type: 'FOOD',
        description: '',
        actions: [ {
            name: 'EAT',
            consume: true,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      FLYER_PINK: {
        name: 'Pink Flyer',
        slug: 'FLYER_PINK', 
        use:  'HOLDS',
        icon: 'FLYER_PINK',
        type: 'FLYER',
        description: '',
        actions: [ {
            name: 'READ',
            consume: false,
            transition: false,
          },],
        stack: 25,
        stacks: [ {
            icon: 'FLYER_PINK_1',
            lessThan: 4,
            greaterThan: 1
          }, {
            icon: 'FLYER_PINK_2',
            lessThan: 11,
            greaterThan: 3
          }, {
            icon: 'FLYER_PINK_3',
            lessThan: 26,
            greaterThan: 10
          }        ],
    },
      PIZZA_BOX_USED: {
        name: 'Pizza Box',
        slug: 'PIZZA_BOX_USED', 
        use:  'HOLDS',
        icon: 'PIZZA_BOX_USED',
        type: 'DELIVERY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      PLASTIC_BAG_1: {
        name: 'Plastic Bag 1',
        slug: 'PLASTIC_BAG_1', 
        use:  'HOLDS',
        icon: 'PLASTIC_BAG_1',
        type: 'BAG',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
slots: '3',
items: []    },
      PLASTIC_BAG_2: {
        name: 'Plastic Bag 2',
        slug: 'PLASTIC_BAG_2', 
        use:  'HOLDS',
        icon: 'PLASTIC_BAG_2',
        type: 'BAG',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
slots: '3',
items: []    },
      POCKET_KNIFE: {
        name: 'Pocket Knife',
        slug: 'POCKET_KNIFE', 
        use:  'USES',
        icon: 'POCKET_KNIFE',
        type: 'TOOL',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      POSTCARD_BACK_1: {
        name: 'Postcard (Back)',
        slug: 'POSTCARD_BACK_1', 
        use:  'HOLDS',
        icon: 'POSTCARD_BACK_1',
        type: 'MAIL',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          }, {
            name: 'FLIP',
            consume: false,
            transition: 'POSTCARD_FRONT_1',
          },],
        stack: 3,
        stacks: [        ],
    },
      POSTCARD_FRONT_1: {
        name: 'Postcard (Front)',
        slug: 'POSTCARD_FRONT_1', 
        use:  'HOLDS',
        icon: 'POSTCARD_FRONT_1',
        type: 'MAIL',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          }, {
            name: 'FLIP',
            consume: false,
            transition: 'POSTCARD_BACK_1',
          },],
        stack: 3,
        stacks: [        ],
    },
      PRETZEL: {
        name: 'Pretzel',
        slug: 'PRETZEL', 
        use:  'HOLDS',
        icon: 'PRETZEL',
        type: 'FOOD',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      BUS_TICKET_PUNCH: {
        name: 'Punched Bus Ticket',
        slug: 'BUS_TICKET_PUNCH', 
        use:  'HOLDS',
        icon: 'BUS_TICKET_PUNCH',
        type: 'TICKET',
        description: '',
        actions: [ {
            name: 'READ',
            consume: false,
            transition: false,
          },],
        stack: 5,
        stacks: [        ],
    },
      CRAYON_PURPLE: {
        name: 'Purple Crayon',
        slug: 'CRAYON_PURPLE', 
        use:  'HOLDS',
        icon: 'CRAYON_PURPLE',
        type: 'CRAYON',
        description: '',
        actions: [ {
            name: 'DRAW',
            consume: false,
            transition: false,
          },],
        stack: 5,
        stacks: [        ],
    },
      RAKE: {
        name: 'Rake',
        slug: 'RAKE', 
        use:  'USES',
        icon: 'RAKE',
        type: 'TOOL',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      CIGARETTE_STRONG: {
        name: 'Red Cigarettes',
        slug: 'CIGARETTE_STRONG', 
        use:  'HOLDS',
        icon: 'CIGARETTE_STRONG',
        type: 'SMOKES',
        description: 'A pack of unfiltered, lung blackening Red Cigarettes. Manufactured by the Reaper Company.',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      CRAYON_RED: {
        name: 'Red Crayon',
        slug: 'CRAYON_RED', 
        use:  'HOLDS',
        icon: 'CRAYON_RED',
        type: 'CRAYON',
        description: '',
        actions: [ {
            name: 'DRAW',
            consume: false,
            transition: false,
          },],
        stack: 5,
        stacks: [        ],
    },
      GELATIN_RED: {
        name: 'Red Jelly-o',
        slug: 'GELATIN_RED', 
        use:  'HOLDS',
        icon: 'GELATIN_RED',
        type: 'FOOD',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      NOTEBOOK_RED: {
        name: 'Red Notebook',
        slug: 'NOTEBOOK_RED', 
        use:  'HOLDS',
        icon: 'NOTEBOOK_RED',
        type: 'NOTEBOOK',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          }, {
            name: 'READ',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      BACKPACK_PURPLE: {
        name: 'School Bag',
        slug: 'BACKPACK_PURPLE', 
        use:  'WEARS',
        icon: 'BACKPACK_PURPLE',
        type: 'BAG',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
slots: '6',
items: []    },
      SCISSORS: {
        name: 'Scissors',
        slug: 'SCISSORS', 
        use:  'USES',
        icon: 'SCISSORS',
        type: 'TOOL',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      SARDINES_PRODUCT: {
        name: 'Sealed Pigeon of the Sea Sardines',
        slug: 'SARDINES_PRODUCT', 
        use:  'HOLDS',
        icon: 'SARDINES_PRODUCT',
        type: 'PRODUCT',
        description: 'A sealed tin of oily, factory-farmed noodle fish.',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      BASKET_BLUE: {
        name: 'Shopping Basket Blue',
        slug: 'BASKET_BLUE', 
        use:  'HOLDS',
        icon: 'BASKET_BLUE',
        type: 'BASKET',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      BASKET_RED: {
        name: 'Shopping Basket Red',
        slug: 'BASKET_RED', 
        use:  'HOLDS',
        icon: 'BASKET_RED',
        type: 'BASKET',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      BASKET_YELLOW: {
        name: 'Shopping Basket Yellow',
        slug: 'BASKET_YELLOW', 
        use:  'HOLDS',
        icon: 'BASKET_YELLOW',
        type: 'BASKET',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      SHOVEL: {
        name: 'Shovel',
        slug: 'SHOVEL', 
        use:  'USES',
        icon: 'SHOVEL',
        type: 'TOOL',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      SODA_BLUE: {
        name: 'SHQUINK-Ahhhh Soda(TM)',
        slug: 'SODA_BLUE', 
        use:  'HOLDS',
        icon: 'SODA_BLUE',
        type: 'DRINK',
        description: 'Feeling parched? Good thing you have a SHQUINK-Ahhhh Soda(TM).',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      SIDEWALK_CHALK_BLUE_: {
        name: 'Sidewalk Chalk (Blue)',
        slug: 'SIDEWALK_CHALK_BLUE_', 
        use:  'HOLDS',
        icon: 'SIDEWALK_CHALK_BLUE_',
        type: 'CHALK',
        description: '',
        actions: [ {
            name: 'DRAW',
            consume: false,
            transition: false,
          },],
        stack: 1,
        stacks: [        ],
    },
      SIDEWALK_CHALK_PINK_: {
        name: 'Sidewalk Chalk (Pink)',
        slug: 'SIDEWALK_CHALK_PINK_', 
        use:  'HOLDS',
        icon: 'SIDEWALK_CHALK_PINK_',
        type: 'CHALK',
        description: '',
        actions: [ {
            name: 'DRAW',
            consume: false,
            transition: false,
          },],
        stack: 1,
        stacks: [        ],
    },
      SIDEWALK_CHALK_YELLOW_: {
        name: 'Sidewalk Chalk (Yellow)',
        slug: 'SIDEWALK_CHALK_YELLOW_', 
        use:  'HOLDS',
        icon: 'SIDEWALK_CHALK_YELLOW_',
        type: 'CHALK',
        description: '',
        actions: [ {
            name: 'DRAW',
            consume: false,
            transition: false,
          },],
        stack: 1,
        stacks: [        ],
    },
      SIDEWALK_CHALK_: {
        name: 'Sidewalk Chalk Discount Pack',
        slug: 'SIDEWALK_CHALK_', 
        use:  'HOLDS',
        icon: 'SIDEWALK_CHALK_',
        type: 'BOX',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          }, {
            name: 'READ',
            consume: false,
            transition: false,
          },],
        stack: 1,
        stacks: [        ],
slots: '3',
items: []    },
      SOUP_CONTAINER_LARGE: {
        name: 'Soup Container (Large)',
        slug: 'SOUP_CONTAINER_LARGE', 
        use:  'HOLDS',
        icon: 'SOUP_CONTAINER_LARGE',
        type: 'DELIVERY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      SOUP_CONTAINER_SMALL: {
        name: 'Soup Container (Small)',
        slug: 'SOUP_CONTAINER_SMALL', 
        use:  'HOLDS',
        icon: 'SOUP_CONTAINER_SMALL',
        type: 'DELIVERY',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      SPADE: {
        name: 'Spade',
        slug: 'SPADE', 
        use:  'USES',
        icon: 'SPADE',
        type: 'TOOL',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      SPRAY_PAINT: {
        name: 'Spray Paint',
        slug: 'SPRAY_PAINT', 
        use:  'USES',
        icon: 'SPRAY_PAINT',
        type: 'TOOL',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      STAPLE_GUN: {
        name: 'Staple Gun',
        slug: 'STAPLE_GUN', 
        use:  'USES',
        icon: 'STAPLE_GUN',
        type: 'TOOL',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          },],
        stack: 1,
        stacks: [        ],
    },
      STAPLES: {
        name: 'Staples',
        slug: 'STAPLES', 
        use:  'HOLDS',
        icon: 'STAPLES',
        type: 'MATERIAL',
        description: '',
        actions: [ {
            name: 'FOLD',
            consume: false,
            transition: false,
          }, {
            name: 'UNFOLD',
            consume: false,
            transition: false,
          },],
        stack: 1,
        stacks: [        ],
    },
      NEWSPAPER_SUNDAY: {
        name: 'Sunday Paper',
        slug: 'NEWSPAPER_SUNDAY', 
        use:  'HOLDS',
        icon: 'NEWSPAPER_SUNDAY',
        type: 'JOURNALISM',
        description: '',
        actions: [ {
            name: 'READ',
            consume: false,
            transition: false,
          }, {
            name: 'LITTER',
            consume: false,
            transition: false,
          }, {
            name: 'CHUCK',
            consume: false,
            transition: false,
          },],
        stack: 3,
        stacks: [        ],
    },
      BREAKFAST_TART_PINK: {
        name: 'Twap Tart',
        slug: 'BREAKFAST_TART_PINK', 
        use:  'HOLDS',
        icon: 'BREAKFAST_TART_PINK',
        type: 'FOOD',
        description: '',
        actions: [ {
            name: 'EAT',
            consume: false,
            transition: false,
          },],
        stack: 1,
        stacks: [        ],
    },
      BREAKFAST_TART_PURPLE: {
        name: 'Twap Tart Berry Blast',
        slug: 'BREAKFAST_TART_PURPLE', 
        use:  'HOLDS',
        icon: 'BREAKFAST_TART_PURPLE',
        type: 'FOOD',
        description: '',
        actions: [ {
            name: 'EAT',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      LUNCH_BAG_USED: {
        name: 'Used Lunch Bag',
        slug: 'LUNCH_BAG_USED', 
        use:  'HOLDS',
        icon: 'LUNCH_BAG_USED',
        type: 'BAG',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
slots: '2',
items: []    },
      PAPER_BAG_USED: {
        name: 'Used Paper Bag',
        slug: 'PAPER_BAG_USED', 
        use:  'HOLDS',
        icon: 'PAPER_BAG_USED',
        type: 'BAG',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
slots: '3',
items: []    },
      CUPCAKE_WHITE: {
        name: 'Vanilla Cupcake',
        slug: 'CUPCAKE_WHITE', 
        use:  'HOLDS',
        icon: 'CUPCAKE_WHITE',
        type: 'FOOD',
        description: '',
        actions: [ {
            name: 'EAT',
            consume: true,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      PUDDING_VANILLA: {
        name: 'Vanilla Pudding',
        slug: 'PUDDING_VANILLA', 
        use:  'HOLDS',
        icon: 'PUDDING_VANILLA',
        type: 'FOOD',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      VHS_WHITE: {
        name: 'VHS Bland',
        slug: 'VHS_WHITE', 
        use:  'HOLDS',
        icon: 'VHS_WHITE',
        type: 'MEDIA',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      VHS_BLUE: {
        name: 'VHS Blue',
        slug: 'VHS_BLUE', 
        use:  'HOLDS',
        icon: 'VHS_BLUE',
        type: 'MEDIA',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      VHS_YELLOW: {
        name: 'VHS Yellow',
        slug: 'VHS_YELLOW', 
        use:  'HOLDS',
        icon: 'VHS_YELLOW',
        type: 'MEDIA',
        description: '',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      CIGARETTE_SLIM: {
        name: 'Warm n’ Toasty Cigarettes',
        slug: 'CIGARETTE_SLIM', 
        use:  'HOLDS',
        icon: 'CIGARETTE_SLIM',
        type: 'SMOKES',
        description: 'A pack of smokey Warm n’ Toasty Cigarettes. Manufactured by the Reaper Company.',
        actions: [],
        stack: 1,
        stacks: [        ],
    },
      WATERING_CAN: {
        name: 'Watering Can',
        slug: 'WATERING_CAN', 
        use:  'USES',
        icon: 'WATERING_CAN',
        type: 'TOOL',
        description: '',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      CRAYON_YELLOW: {
        name: 'Yellow Crayon',
        slug: 'CRAYON_YELLOW', 
        use:  'HOLDS',
        icon: 'CRAYON_YELLOW',
        type: 'CRAYON',
        description: '',
        actions: [ {
            name: 'DRAW',
            consume: false,
            transition: false,
          },],
        stack: 5,
        stacks: [        ],
    },
      CUPCAKE_YELLOW: {
        name: 'Yellow Cupcake',
        slug: 'CUPCAKE_YELLOW', 
        use:  'HOLDS',
        icon: 'CUPCAKE_YELLOW',
        type: 'FOOD',
        description: '',
        actions: [ {
            name: 'EAT',
            consume: true,
            transition: false,
          },],
        stack: 0,
        stacks: [        ],
    },
      ZENER_1: {
        name: 'Zener Card (Circle)',
        slug: 'ZENER_1', 
        use:  'HOLDS',
        icon: 'ZENER_1',
        type: 'CARD',
        description: '',
        actions: [ {
            name: 'FLIP',
            consume: false,
            transition: false,
          },],
        stack: 1,
        stacks: [        ],
    },
      ZENER_2: {
        name: 'Zener Card (Plus)',
        slug: 'ZENER_2', 
        use:  'HOLDS',
        icon: 'ZENER_2',
        type: 'CARD',
        description: '',
        actions: [ {
            name: 'FLIP',
            consume: false,
            transition: false,
          },],
        stack: 1,
        stacks: [        ],
    },
      ZENER_4: {
        name: 'Zener Card (Square)',
        slug: 'ZENER_4', 
        use:  'HOLDS',
        icon: 'ZENER_4',
        type: 'CARD',
        description: '',
        actions: [ {
            name: 'FLIP',
            consume: false,
            transition: false,
          },],
        stack: 1,
        stacks: [        ],
    },
      ZENER_5: {
        name: 'Zener Card (Star)',
        slug: 'ZENER_5', 
        use:  'HOLDS',
        icon: 'ZENER_5',
        type: 'CARD',
        description: '',
        actions: [ {
            name: 'FLIP',
            consume: false,
            transition: false,
          },],
        stack: 1,
        stacks: [        ],
    },
      ZENER_3: {
        name: 'Zener Card (Waves)',
        slug: 'ZENER_3', 
        use:  'HOLDS',
        icon: 'ZENER_3',
        type: 'CARD',
        description: '',
        actions: [ {
            name: 'FLIP',
            consume: false,
            transition: false,
          },],
        stack: 1,
        stacks: [        ],
    },
  };
export default ITEMS;
