const ITEMS = {
      APPLE: {
        name: 'Apple',
        slug: 'APPLE', 
        use:  'HOLDS',
        icon: 'APPLE',
        type: 'FOOD',
        actions: [ {
            name: 'EAT',
            consume: false,
            transition: 'APPLE_TRASH',
          },],
    },
      APPLE_TRASH: {
        name: 'Apple Core',
        slug: 'APPLE_TRASH', 
        use:  'HOLDS',
        icon: 'APPLE_TRASH',
        type: 'TRASH',
        actions: [ {
            name: 'CRUMPLE',
            consume: false,
            transition: false,
          },],
    },
      BANANA: {
        name: 'Banana',
        slug: 'BANANA', 
        use:  'HOLDS',
        icon: 'BANANA',
        type: 'FOOD',
        actions: [ {
            name: 'EAT',
            consume: false,
            transition: 'BANANA_TRASH',
          },],
    },
      BANANA_TRASH: {
        name: 'Banana Peel',
        slug: 'BANANA_TRASH', 
        use:  'HOLDS',
        icon: 'BANANA_TRASH',
        type: 'TRASH',
        actions: [ {
            name: 'CRUMPLE',
            consume: false,
            transition: false,
          },],
    },
      MUFFIN_BERRY: {
        name: 'Berry Muffin',
        slug: 'MUFFIN_BERRY', 
        use:  'HOLDS',
        icon: 'MUFFIN_BERRY',
        type: 'FOOD',
        actions: [ {
            name: 'EAT',
            consume: true,
            transition: false,
          },],
    },
      NOTEBOOK_BLUE: {
        name: 'Blue Notebook',
        slug: 'NOTEBOOK_BLUE', 
        use:  'HOLDS',
        icon: 'NOTEBOOK_BLUE',
        type: 'NOTEBOOK',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          }, {
            name: 'READ',
            consume: false,
            transition: false,
          },],
    },
      BANANA_BRUISED: {
        name: 'Bruised Banana',
        slug: 'BANANA_BRUISED', 
        use:  'HOLDS',
        icon: 'BANANA_BRUISED',
        type: 'FOOD',
        actions: [ {
            name: 'EAT',
            consume: false,
            transition: 'BANANA_TRASH',
          },],
    },
      SODA_RED: {
        name: 'Cane Soda',
        slug: 'SODA_RED', 
        use:  'HOLDS',
        icon: 'SODA_RED',
        type: 'DRINK',
        actions: [ {
            name: 'DRINK',
            consume: false,
            transition: 'SODA_RED_TRASH',
          },],
    },
      BACKPACK_CANVAS: {
        name: 'Canvas Backpack',
        slug: 'BACKPACK_CANVAS', 
        use:  'WEARS',
        icon: 'BACKPACK_CANVAS',
        type: 'BAG',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          },],
slots: '6',
items: []    },
      CASSETTE_BLACK: {
        name: 'Cassette Tape Black',
        slug: 'CASSETTE_BLACK', 
        use:  'HOLDS',
        icon: 'CASSETTE_BLACK',
        type: 'MEDIA',
        actions: [],
    },
      CASSETTE_BLUE: {
        name: 'Cassette Tape Blue',
        slug: 'CASSETTE_BLUE', 
        use:  'HOLDS',
        icon: 'CASSETTE_BLUE',
        type: 'MEDIA',
        actions: [],
    },
      CASSETTE_RED: {
        name: 'Cassette Tape Red',
        slug: 'CASSETTE_RED', 
        use:  'HOLDS',
        icon: 'CASSETTE_RED',
        type: 'MEDIA',
        actions: [],
    },
      CASSETTE_YELLOW: {
        name: 'Cassette Tape Yellow',
        slug: 'CASSETTE_YELLOW', 
        use:  'HOLDS',
        icon: 'CASSETTE_YELLOW',
        type: 'MEDIA',
        actions: [],
    },
      CHINESE_FOOD: {
        name: 'Chinese Food',
        slug: 'CHINESE_FOOD', 
        use:  'HOLDS',
        icon: 'CHINESE_FOOD',
        type: 'DELIVERY',
        actions: [],
    },
      CHINESE_FOOD_MARKED: {
        name: 'Chinese Food (Marked)',
        slug: 'CHINESE_FOOD_MARKED', 
        use:  'HOLDS',
        icon: 'CHINESE_FOOD_MARKED',
        type: 'DELIVERY',
        actions: [],
    },
      CUPCAKE_CHOCOLATE: {
        name: 'Chocolate Cupcake',
        slug: 'CUPCAKE_CHOCOLATE', 
        use:  'HOLDS',
        icon: 'CUPCAKE_CHOCOLATE',
        type: 'FOOD',
        actions: [],
    },
      PUDDING_CHOCOLATE: {
        name: 'Chocolate Pudding',
        slug: 'PUDDING_CHOCOLATE', 
        use:  'HOLDS',
        icon: 'PUDDING_CHOCOLATE',
        type: 'FOOD',
        actions: [],
    },
      LUNCH_BAG_CLEAN: {
        name: 'Clean Lunch Bag',
        slug: 'LUNCH_BAG_CLEAN', 
        use:  'HOLDS',
        icon: 'LUNCH_BAG_CLEAN',
        type: 'BAG',
        actions: [],
slots: '2',
items: []    },
      PAPER_BAG_CLEAN: {
        name: 'Clean Paper Bag',
        slug: 'PAPER_BAG_CLEAN', 
        use:  'HOLDS',
        icon: 'PAPER_BAG_CLEAN',
        type: 'BAG',
        actions: [],
slots: '3',
items: []    },
      CLOVES: {
        name: 'Cloves',
        slug: 'CLOVES', 
        use:  'HOLDS',
        icon: 'CLOVES',
        type: 'SMOKES',
        actions: [],
    },
      COOKIE: {
        name: 'Cookie',
        slug: 'COOKIE', 
        use:  'HOLDS',
        icon: 'COOKIE',
        type: 'FOOD',
        actions: [],
    },
      BEER: {
        name: 'Driver’s Brew',
        slug: 'BEER', 
        use:  'HOLDS',
        icon: 'BEER',
        type: 'ALCOHOL',
        actions: [],
    },
      SODA_RED_TRASH: {
        name: 'Empty Cane Soda Can',
        slug: 'SODA_RED_TRASH', 
        use:  'HOLDS',
        icon: 'SODA_RED_TRASH',
        type: 'TRASH',
        actions: [ {
            name: 'CRUMPLE',
            consume: false,
            transition: false,
          },],
    },
      ENVELOPE_BACK_1: {
        name: 'Envelope (Back)',
        slug: 'ENVELOPE_BACK_1', 
        use:  'HOLDS',
        icon: 'ENVELOPE_BACK_1',
        type: 'MAIL',
        actions: [],
    },
      ENVELOPE_FRONT_1: {
        name: 'Envelope (Front)',
        slug: 'ENVELOPE_FRONT_1', 
        use:  'HOLDS',
        icon: 'ENVELOPE_FRONT_1',
        type: 'MAIL',
        actions: [],
    },
      FLOPPY_BLUE: {
        name: 'Floppy Disk Blue',
        slug: 'FLOPPY_BLUE', 
        use:  'HOLDS',
        icon: 'FLOPPY_BLUE',
        type: 'MEDIA',
        actions: [],
    },
      FLOPPY_GREEN: {
        name: 'Floppy Disk Green',
        slug: 'FLOPPY_GREEN', 
        use:  'HOLDS',
        icon: 'FLOPPY_GREEN',
        type: 'MEDIA',
        actions: [],
    },
      FLOPPY_RED: {
        name: 'Floppy Disk Red',
        slug: 'FLOPPY_RED', 
        use:  'HOLDS',
        icon: 'FLOPPY_RED',
        type: 'MEDIA',
        actions: [],
    },
      FLOPPY_YELLOW: {
        name: 'Floppy Disk Yellow',
        slug: 'FLOPPY_YELLOW', 
        use:  'HOLDS',
        icon: 'FLOPPY_YELLOW',
        type: 'MEDIA',
        actions: [],
    },
      SODA_GREEN: {
        name: 'Fresco Lime-o Soda(TM)',
        slug: 'SODA_GREEN', 
        use:  'HOLDS',
        icon: 'SODA_GREEN',
        type: 'DRINK',
        actions: [],
    },
      PIZZA_BOX_CLEAN: {
        name: 'Fresh Pizza Box',
        slug: 'PIZZA_BOX_CLEAN', 
        use:  'HOLDS',
        icon: 'PIZZA_BOX_CLEAN',
        type: 'DELIVERY',
        actions: [],
    },
      LUNCH_BAG_GREASY: {
        name: 'Greasy Lunch Bag',
        slug: 'LUNCH_BAG_GREASY', 
        use:  'HOLDS',
        icon: 'LUNCH_BAG_GREASY',
        type: 'BAG',
        actions: [],
slots: '2',
items: []    },
      PAPER_BAG_GREASY: {
        name: 'Greasy Paper Bag',
        slug: 'PAPER_BAG_GREASY', 
        use:  'HOLDS',
        icon: 'PAPER_BAG_GREASY',
        type: 'BAG',
        actions: [],
slots: '3',
items: []    },
      PIZZA_BOX_GREASY: {
        name: 'Greasy Pizza Box',
        slug: 'PIZZA_BOX_GREASY', 
        use:  'HOLDS',
        icon: 'PIZZA_BOX_GREASY',
        type: 'DELIVERY',
        actions: [],
    },
      BACKPACK_GREEN: {
        name: 'Green Backpack',
        slug: 'BACKPACK_GREEN', 
        use:  'WEARS',
        icon: 'BACKPACK_GREEN',
        type: 'BAG',
        actions: [],
slots: '6',
items: []    },
      NOTEBOOK_GREEN: {
        name: 'Green Notebook',
        slug: 'NOTEBOOK_GREEN', 
        use:  'HOLDS',
        icon: 'NOTEBOOK_GREEN',
        type: 'NOTEBOOK',
        actions: [ {
            name: 'OPEN',
            consume: false,
            transition: false,
          }, {
            name: 'READ',
            consume: false,
            transition: false,
          },],
    },
      VHS_HOME: {
        name: 'Home Video VHS',
        slug: 'VHS_HOME', 
        use:  'HOLDS',
        icon: 'VHS_HOME',
        type: 'MEDIA',
        actions: [],
    },
      INSTANT_NOODLES_RED: {
        name: 'Instant Noodles Beef',
        slug: 'INSTANT_NOODLES_RED', 
        use:  'HOLDS',
        icon: 'INSTANT_NOODLES_RED',
        type: 'FOOD',
        actions: [ {
            name: 'EAT',
            consume: false,
            transition: false,
          },],
    },
      INSTANT_NOODLES_ORANGE: {
        name: 'Instant Noodles Chicken',
        slug: 'INSTANT_NOODLES_ORANGE', 
        use:  'HOLDS',
        icon: 'INSTANT_NOODLES_ORANGE',
        type: 'FOOD',
        actions: [ {
            name: 'EAT',
            consume: false,
            transition: false,
          },],
    },
      INSTANT_NOODLES_BLUE: {
        name: 'Instant Noodles Shrimp',
        slug: 'INSTANT_NOODLES_BLUE', 
        use:  'HOLDS',
        icon: 'INSTANT_NOODLES_BLUE',
        type: 'FOOD',
        actions: [ {
            name: 'EAT',
            consume: false,
            transition: false,
          },],
    },
      INSTANT_NOODLES_GREEN: {
        name: 'Instant Noodles Vegetables',
        slug: 'INSTANT_NOODLES_GREEN', 
        use:  'HOLDS',
        icon: 'INSTANT_NOODLES_GREEN',
        type: 'FOOD',
        actions: [],
    },
      KEY_1: {
        name: 'Key 1',
        slug: 'KEY_1', 
        use:  'HOLDS',
        icon: 'KEY_1',
        type: 'KEY',
        actions: [],
    },
      KEY_10: {
        name: 'Key 10',
        slug: 'KEY_10', 
        use:  'HOLDS',
        icon: 'KEY_10',
        type: 'KEY',
        actions: [],
    },
      KEY_11: {
        name: 'Key 11',
        slug: 'KEY_11', 
        use:  'HOLDS',
        icon: 'KEY_11',
        type: 'KEY',
        actions: [],
    },
      KEY_12: {
        name: 'Key 12',
        slug: 'KEY_12', 
        use:  'HOLDS',
        icon: 'KEY_12',
        type: 'KEY',
        actions: [],
    },
      KEY_2: {
        name: 'Key 2',
        slug: 'KEY_2', 
        use:  'HOLDS',
        icon: 'KEY_2',
        type: 'KEY',
        actions: [],
    },
      KEY_3: {
        name: 'Key 3',
        slug: 'KEY_3', 
        use:  'HOLDS',
        icon: 'KEY_3',
        type: 'KEY',
        actions: [],
    },
      KEY_4: {
        name: 'Key 4',
        slug: 'KEY_4', 
        use:  'HOLDS',
        icon: 'KEY_4',
        type: 'KEY',
        actions: [],
    },
      KEY_5: {
        name: 'Key 5',
        slug: 'KEY_5', 
        use:  'HOLDS',
        icon: 'KEY_5',
        type: 'KEY',
        actions: [],
    },
      KEY_6: {
        name: 'Key 6',
        slug: 'KEY_6', 
        use:  'HOLDS',
        icon: 'KEY_6',
        type: 'KEY',
        actions: [],
    },
      KEY_7: {
        name: 'Key 7',
        slug: 'KEY_7', 
        use:  'HOLDS',
        icon: 'KEY_7',
        type: 'KEY',
        actions: [],
    },
      KEY_8: {
        name: 'Key 8',
        slug: 'KEY_8', 
        use:  'HOLDS',
        icon: 'KEY_8',
        type: 'KEY',
        actions: [],
    },
      KEY_9: {
        name: 'Key 9',
        slug: 'KEY_9', 
        use:  'HOLDS',
        icon: 'KEY_9',
        type: 'KEY',
        actions: [],
    },
      BACKPACK_BROWN: {
        name: 'Leather Rucksack',
        slug: 'BACKPACK_BROWN', 
        use:  'WEARS',
        icon: 'BACKPACK_BROWN',
        type: 'BAG',
        actions: [],
slots: '6',
items: []    },
      LIBRARY_CARD: {
        name: 'Library Card',
        slug: 'LIBRARY_CARD', 
        use:  'HOLDS',
        icon: 'LIBRARY_CARD',
        type: 'ID',
        actions: [],
    },
      CIGARETTE_MENTHOL: {
        name: 'Menthol Frost',
        slug: 'CIGARETTE_MENTHOL', 
        use:  'HOLDS',
        icon: 'CIGARETTE_MENTHOL',
        type: 'SMOKES',
        actions: [],
    },
      MUFFIN: {
        name: 'Muffin',
        slug: 'MUFFIN', 
        use:  'HOLDS',
        icon: 'MUFFIN',
        type: 'FOOD',
        actions: [],
    },
      NEWSPAPER: {
        name: 'Newspaper',
        slug: 'NEWSPAPER', 
        use:  'HOLDS',
        icon: 'NEWSPAPER',
        type: 'JOURNALISM',
        actions: [ {
            name: 'READ',
            consume: false,
            transition: false,
          }, {
            name: 'LITTER',
            consume: false,
            transition: false,
          }, {
            name: 'CRUMPLE',
            consume: false,
            transition: false,
          },],
    },
      SARDINES: {
        name: 'Open Pigeon of the Sea Sardines',
        slug: 'SARDINES', 
        use:  'HOLDS',
        icon: 'SARDINES',
        type: 'FOOD',
        actions: [],
    },
      PIZZA_BOX_USED: {
        name: 'Pizza Box',
        slug: 'PIZZA_BOX_USED', 
        use:  'HOLDS',
        icon: 'PIZZA_BOX_USED',
        type: 'DELIVERY',
        actions: [],
    },
      PLASTIC_BAG_1: {
        name: 'Plastic Bag 1',
        slug: 'PLASTIC_BAG_1', 
        use:  'HOLDS',
        icon: 'PLASTIC_BAG_1',
        type: 'BAG',
        actions: [],
slots: '3',
items: []    },
      PLASTIC_BAG_2: {
        name: 'Plastic Bag 2',
        slug: 'PLASTIC_BAG_2', 
        use:  'HOLDS',
        icon: 'PLASTIC_BAG_2',
        type: 'BAG',
        actions: [],
slots: '3',
items: []    },
      POCKET_KNIFE: {
        name: 'Pocket Knife',
        slug: 'POCKET_KNIFE', 
        use:  'USES',
        icon: 'POCKET_KNIFE',
        type: 'TOOL',
        actions: [],
    },
      POSTCARD_BACK_1: {
        name: 'Postcard (Back)',
        slug: 'POSTCARD_BACK_1', 
        use:  'HOLDS',
        icon: 'POSTCARD_BACK_1',
        type: 'MAIL',
        actions: [],
    },
      POSTCARD_FRONT_1: {
        name: 'Postcard (Front)',
        slug: 'POSTCARD_FRONT_1', 
        use:  'HOLDS',
        icon: 'POSTCARD_FRONT_1',
        type: 'MAIL',
        actions: [],
    },
      PRETZEL: {
        name: 'Pretzel',
        slug: 'PRETZEL', 
        use:  'HOLDS',
        icon: 'PRETZEL',
        type: 'FOOD',
        actions: [],
    },
      CIGARETTE_STRONG: {
        name: 'Red Cigarettes',
        slug: 'CIGARETTE_STRONG', 
        use:  'HOLDS',
        icon: 'CIGARETTE_STRONG',
        type: 'SMOKES',
        actions: [],
    },
      GELATIN_RED: {
        name: 'Red Jelly-o',
        slug: 'GELATIN_RED', 
        use:  'HOLDS',
        icon: 'GELATIN_RED',
        type: 'FOOD',
        actions: [],
    },
      BACKPACK_PURPLE: {
        name: 'School Bag',
        slug: 'BACKPACK_PURPLE', 
        use:  'WEARS',
        icon: 'BACKPACK_PURPLE',
        type: 'BAG',
        actions: [],
slots: '6',
items: []    },
      SARDINES_PRODUCT: {
        name: 'Sealed Pigeon of the Sea Sardines',
        slug: 'SARDINES_PRODUCT', 
        use:  'HOLDS',
        icon: 'SARDINES_PRODUCT',
        type: 'PRODUCT',
        actions: [],
    },
      BASKET_BLUE: {
        name: 'Shopping Basket Blue',
        slug: 'BASKET_BLUE', 
        use:  'HOLDS',
        icon: 'BASKET_BLUE',
        type: 'BASKET',
        actions: [],
    },
      BASKET_RED: {
        name: 'Shopping Basket Red',
        slug: 'BASKET_RED', 
        use:  'HOLDS',
        icon: 'BASKET_RED',
        type: 'BASKET',
        actions: [],
    },
      BASKET_YELLOW: {
        name: 'Shopping Basket Yellow',
        slug: 'BASKET_YELLOW', 
        use:  'HOLDS',
        icon: 'BASKET_YELLOW',
        type: 'BASKET',
        actions: [],
    },
      SODA_BLUE: {
        name: 'SHQUINK-Ahhhh Soda(TM)',
        slug: 'SODA_BLUE', 
        use:  'HOLDS',
        icon: 'SODA_BLUE',
        type: 'DRINK',
        actions: [],
    },
      SOUP_CONTAINER_LARGE: {
        name: 'Soup Container (Large)',
        slug: 'SOUP_CONTAINER_LARGE', 
        use:  'HOLDS',
        icon: 'SOUP_CONTAINER_LARGE',
        type: 'DELIVERY',
        actions: [],
    },
      SOUP_CONTAINER_SMALL: {
        name: 'Soup Container (Small)',
        slug: 'SOUP_CONTAINER_SMALL', 
        use:  'HOLDS',
        icon: 'SOUP_CONTAINER_SMALL',
        type: 'DELIVERY',
        actions: [],
    },
      NEWSPAPER_SUNDAY: {
        name: 'Sunday Paper',
        slug: 'NEWSPAPER_SUNDAY', 
        use:  'HOLDS',
        icon: 'NEWSPAPER_SUNDAY',
        type: 'JOURNALISM',
        actions: [ {
            name: 'READ',
            consume: false,
            transition: false,
          }, {
            name: 'LITTER',
            consume: false,
            transition: false,
          }, {
            name: 'CRUMPLE',
            consume: false,
            transition: false,
          },],
    },
      BREAKFAST_TART_PINK: {
        name: 'Twap Tart',
        slug: 'BREAKFAST_TART_PINK', 
        use:  'HOLDS',
        icon: 'BREAKFAST_TART_PINK',
        type: 'FOOD',
        actions: [ {
            name: 'EAT',
            consume: false,
            transition: false,
          },],
    },
      BREAKFAST_TART_PURPLE: {
        name: 'Twap Tart Berry Blast',
        slug: 'BREAKFAST_TART_PURPLE', 
        use:  'HOLDS',
        icon: 'BREAKFAST_TART_PURPLE',
        type: 'FOOD',
        actions: [ {
            name: 'EAT',
            consume: false,
            transition: false,
          },],
    },
      LUNCH_BAG_USED: {
        name: 'Used Lunch Bag',
        slug: 'LUNCH_BAG_USED', 
        use:  'HOLDS',
        icon: 'LUNCH_BAG_USED',
        type: 'BAG',
        actions: [],
slots: '2',
items: []    },
      PAPER_BAG_USED: {
        name: 'Used Paper Bag',
        slug: 'PAPER_BAG_USED', 
        use:  'HOLDS',
        icon: 'PAPER_BAG_USED',
        type: 'BAG',
        actions: [],
slots: '3',
items: []    },
      PUDDING_VANILLA: {
        name: 'Vanilla Pudding',
        slug: 'PUDDING_VANILLA', 
        use:  'HOLDS',
        icon: 'PUDDING_VANILLA',
        type: 'FOOD',
        actions: [],
    },
      VHS_WHITE: {
        name: 'VHS Bland',
        slug: 'VHS_WHITE', 
        use:  'HOLDS',
        icon: 'VHS_WHITE',
        type: 'MEDIA',
        actions: [],
    },
      VHS_BLUE: {
        name: 'VHS Blue',
        slug: 'VHS_BLUE', 
        use:  'HOLDS',
        icon: 'VHS_BLUE',
        type: 'MEDIA',
        actions: [],
    },
      VHS_YELLOW: {
        name: 'VHS Yellow',
        slug: 'VHS_YELLOW', 
        use:  'HOLDS',
        icon: 'VHS_YELLOW',
        type: 'MEDIA',
        actions: [],
    },
      CIGARETTE_SLIM: {
        name: 'Warm n’ Toasty Cigarettes',
        slug: 'CIGARETTE_SLIM', 
        use:  'HOLDS',
        icon: 'CIGARETTE_SLIM',
        type: 'SMOKES',
        actions: [],
    },
      CUPCAKE_YELLOW: {
        name: 'Yellow Cupcake',
        slug: 'CUPCAKE_YELLOW', 
        use:  'HOLDS',
        icon: 'CUPCAKE_YELLOW',
        type: 'FOOD',
        actions: [],
    },
  };
export default ITEMS;
