          const STATUS = {
                          CARBONATION: {
                  name: 'Carbonation',
                  slug: 'CARBONATION',
                  decays: false,
                  decayLength: 0,
                  transition: '',
                  fx_start: '',
                  fx: 'CARBONATION',
                  fx_end: ''              },
                          COLD: {
                  name: 'Cold',
                  slug: 'COLD',
                  decays: true,
                  decayLength: 180,
                  transition: 'LUKEWARM',
                  fx_start: '',
                  fx: '',
                  fx_end: ''              },
                          FROZEN: {
                  name: 'Frozen',
                  slug: 'FROZEN',
                  decays: true,
                  decayLength: 60,
                  transition: 'THAWING',
                  fx_start: '',
                  fx: '',
                  fx_end: ''              },
                          LUCKY: {
                  name: 'Lucky',
                  slug: 'LUCKY',
                  decays: false,
                  decayLength: 0,
                  transition: '',
                  fx_start: 'SPARKLE_',
                  fx: '',
                  fx_end: 'SPARKLE_'              },
                          LUKEWARM: {
                  name: 'Lukewarm',
                  slug: 'LUKEWARM',
                  decays: true,
                  decayLength: 180,
                  transition: '',
                  fx_start: '',
                  fx: '',
                  fx_end: ''              },
                          MELTED: {
                  name: 'Melted',
                  slug: 'MELTED',
                  decays: false,
                  decayLength: 0,
                  transition: '',
                  fx_start: '',
                  fx: '',
                  fx_end: ''              },
                          MELTING: {
                  name: 'Melting',
                  slug: 'MELTING',
                  decays: true,
                  decayLength: 120,
                  transition: 'MELTED',
                  fx_start: '',
                  fx: '',
                  fx_end: ''              },
                          PRAYER_CANDLE_LIT_HIGH: {
                  name: 'Prayer Candle Lit High',
                  slug: 'PRAYER_CANDLE_LIT_HIGH',
                  decays: true,
                  decayLength: 0,
                  transition: '',
                  fx_start: '',
                  fx: 'PRAYER_CANDLE_FRAME_HIGH',
                  fx_end: ''              },
                          PRAYER_CANDLE_LIT_MID: {
                  name: 'Prayer Candle Lit Mid',
                  slug: 'PRAYER_CANDLE_LIT_MID',
                  decays: false,
                  decayLength: 0,
                  transition: '',
                  fx_start: '',
                  fx: 'PRAYER_CANDLE_FRAME_MID',
                  fx_end: ''              },
                          RINGING: {
                  name: 'Ringing',
                  slug: 'RINGING',
                  decays: true,
                  decayLength: 10,
                  transition: '',
                  fx_start: '',
                  fx: '',
                  fx_end: ''              },
                          STEAMING: {
                  name: 'Steaming',
                  slug: 'STEAMING',
                  decays: true,
                  decayLength: 120,
                  transition: 'WARM',
                  fx_start: 'STEAM_START_',
                  fx: 'STEAM_REPEAT_',
                  fx_end: 'STEAM_END_'              },
                          STINKING: {
                  name: 'Stinking',
                  slug: 'STINKING',
                  decays: false,
                  decayLength: 0,
                  transition: '',
                  fx_start: 'STINK_START',
                  fx: 'STINK_REPEAT',
                  fx_end: 'STINK_END',
                  
                  data_key: 'ODOR',
                  dataCompare: '>',
                  dataValue: 3
                                },
                          THAWING: {
                  name: 'Thawing',
                  slug: 'THAWING',
                  decays: true,
                  decayLength: 120,
                  transition: 'MELTING',
                  fx_start: '',
                  fx: '',
                  fx_end: ''              },
                          WARM: {
                  name: 'Warm',
                  slug: 'WARM',
                  decays: true,
                  decayLength: 120,
                  transition: 'LUKEWARM',
                  fx_start: '',
                  fx: '',
                  fx_end: ''              }
                      };
          export default STATUS;
          